-- =========================================================================
-- ESCO MIGRATION — PHASE 1: FOUNDATION
-- =========================================================================
--
-- АВТОГЕНЕРОВАНО tools/generate-esco-phase1.py — НЕ редагувати вручну.
-- Якщо треба виправити рядок — редагуй xlsx у PerenosTablu/ і перезапусти
-- скрипт, або ALTER/UPDATE окремим файлом поверх.
--
-- Переносимо до public.<table> з tenant_id='esco' ~53 рядків:
--   system_settings             25 рядків
--   app_content                  7 рядків
--   distribution_template        6 рядків
--   notifications                6 рядків
--   clients_directory            3 рядків
--   staff                        4 рядків
--   owner_account                2 рядків
--
-- Ідемпотентно: ON CONFLICT (tenant_id, <legacy_id>) DO NOTHING. Повторний
-- запуск нічого не дублює.
-- =========================================================================

BEGIN;

-- ── 1. Додаткові колонки на owner_account (Phase 1 рішення Q3=а) ────────
ALTER TABLE public.owner_account ADD COLUMN IF NOT EXISTS legacy_id text;
ALTER TABLE public.owner_account ADD COLUMN IF NOT EXISTS access_scope text;
ALTER TABLE public.owner_account ADD COLUMN IF NOT EXISTS notes text;

-- ── 2. UNIQUE індекси — обовʼязкові для ON CONFLICT у INSERT'ах нижче ──
CREATE UNIQUE INDEX IF NOT EXISTS system_settings_tenant_sid_uidx ON public.system_settings (tenant_id, setting_id);
CREATE UNIQUE INDEX IF NOT EXISTS app_content_tenant_cid_uidx ON public.app_content (tenant_id, content_id);
CREATE UNIQUE INDEX IF NOT EXISTS distribution_template_tenant_tid_uidx ON public.distribution_template (tenant_id, tmpl_id);
CREATE UNIQUE INDEX IF NOT EXISTS notifications_tenant_nid_uidx ON public.notifications (tenant_id, notif_id);
CREATE UNIQUE INDEX IF NOT EXISTS clients_directory_tenant_cid_uidx ON public.clients_directory (tenant_id, cli_id);
CREATE UNIQUE INDEX IF NOT EXISTS staff_tenant_sid_uidx ON public.staff (tenant_id, staff_id);
CREATE UNIQUE INDEX IF NOT EXISTS owner_account_tenant_login_uidx ON public.owner_account (tenant_id, login);

-- ── system_settings (25 рядків) ─────────────────────────────────────
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-001', 'Компанія', 'company_name', 'EscoExpress', 'Назва компанії', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-002', 'Компанія', 'company_logo', 'https://drive.google.com/logo.png', 'Посилання на лого', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник; Оновити лого тут') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-003', 'Компанія', 'company_phone', '+380991234567', 'Телефон компанії', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-004', 'Компанія', 'company_email', 'info@escoexpress.com', 'Email компанії', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-005', 'Компанія', 'company_address', 'вул. Хрещатик 1, Київ', 'Адреса офісу', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-006', 'Компанія', 'company_website', 'https://escoexpress.com', 'Сайт компанії', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-007', 'Компанія', 'company_instagram', '@escoexpress', 'Instagram', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-008', 'Компанія', 'company_telegram', '@escoexpress_bot', 'Telegram бот', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-009', 'Система', 'default_currency', 'CHF', 'Валюта за замовчуванням', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-010', 'Система', 'system_language', 'UA', 'Мова системи', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник; UA/EN') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-011', 'Система', 'session_timeout', '30', 'Таймаут сесії (хв)', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-012', 'Система', 'crm_version', '1.0', 'Версія CRM', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-013', 'Система', 'archive_after_days', '90', 'Архівувати через N днів', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-014', 'Система', 'debt_reminder_days', '7', 'Нагадування боргу через N днів', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-015', 'Система', 'supported_currencies', 'UAH,CHF,EUR,PLN,CZK,USD', 'Підтримувані валюти', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-016', 'Система', 'max_seats_default', '7', 'Місць в авто за замовч', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-017', 'API', 'smartsender_token', 'token_here', 'Токен Смартсендера', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник; Оновлювати щомісяця') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-018', 'API', 'claude_api_key', 'sk-ant-here', 'Claude AI API ключ', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник; Для AI асистента') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-019', 'API', 'passengers_sheet_id', '1DDNX75p...', 'ID таблиці Passengers_crm', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-020', 'API', 'posylki_sheet_id', '1178pz5g...', 'ID таблиці Posylki_crm', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-021', 'API', 'marhrut_sheet_id', '1Lqk7_UW...', 'ID таблиці Marhrut_crm', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-022', 'API', 'kliyentu_sheet_id', '1-QIHhzj...', 'ID таблиці Kliyentu_crm', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-023', 'API', 'finance_sheet_id', 'new_id_here', 'ID таблиці Finance_crm', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-024', 'API', 'archive_sheet_id', '1njYUWYQ...', 'ID таблиці Archive_crm', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;
INSERT INTO public.system_settings (tenant_id, setting_id, setting_section, setting_name, setting_value, setting_description, updated_date, notes) VALUES ('esco', 'SET-025', 'API', 'config_sheet_id', 'this_file_id', 'ID таблиці Config_crm', '2023-01-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, setting_id) DO NOTHING;

-- ── app_content (7 рядків) ─────────────────────────────────────
INSERT INTO public.app_content (tenant_id, content_id, content_type, content_name, language, content_text, is_active, updated_date, notes) VALUES ('esco', 'CNT-001', 'Умови перевезення', 'Умови перевезення пасажирів', 'uk', 'Компанія EscoExpress здійснює перевезення...', true, '2025-06-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, content_id) DO NOTHING;
INSERT INTO public.app_content (tenant_id, content_id, content_type, content_name, language, content_text, is_active, updated_date, notes) VALUES ('esco', 'CNT-002', 'Тарифи пасажири', 'Ціна УК→ЄВ Цюріх', 'uk', '200 CHF стандарт | 250 CHF VIP', true, '2025-06-01 00:00:00'::timestamptz, 'Хто змінив: Менеджер') ON CONFLICT (tenant_id, content_id) DO NOTHING;
INSERT INTO public.app_content (tenant_id, content_id, content_type, content_name, language, content_text, is_active, updated_date, notes) VALUES ('esco', 'CNT-003', 'Тарифи посилки', 'Ціна за кг УК→ЄВ', 'uk', 'від 20 CHF/кг', true, '2025-06-01 00:00:00'::timestamptz, 'Хто змінив: Менеджер') ON CONFLICT (tenant_id, content_id) DO NOTHING;
INSERT INTO public.app_content (tenant_id, content_id, content_type, content_name, language, content_text, is_active, updated_date, notes) VALUES ('esco', 'CNT-004', 'Інструкція посилки', 'Як передати посилку', 'uk', '1. Запакуйте посилку... 2. Зателефонуйте...', true, '2025-06-01 00:00:00'::timestamptz, 'Хто змінив: Власник') ON CONFLICT (tenant_id, content_id) DO NOTHING;
INSERT INTO public.app_content (tenant_id, content_id, content_type, content_name, language, content_text, is_active, updated_date, notes) VALUES ('esco', 'CNT-005', 'Контакти', 'Телефон компанії', 'uk', '+380991234567', true, '2025-06-01 00:00:00'::timestamptz, 'Хто змінив: Менеджер') ON CONFLICT (tenant_id, content_id) DO NOTHING;
INSERT INTO public.app_content (tenant_id, content_id, content_type, content_name, language, content_text, is_active, updated_date, notes) VALUES ('esco', 'CNT-006', 'Точки', 'Адреса офісу Київ', 'uk', 'вул. Хрещатик 1, Київ — пн-пт 9:00-18:00', true, '2025-06-01 00:00:00'::timestamptz, 'Хто змінив: Менеджер') ON CONFLICT (tenant_id, content_id) DO NOTHING;
INSERT INTO public.app_content (tenant_id, content_id, content_type, content_name, language, content_text, is_active, updated_date, notes) VALUES ('esco', 'CNT-007', 'Точки', 'Адреса офісу Цюріх', 'uk', 'Hauptstrasse 5, Zürich — пн-пт 10:00-19:00', true, '2025-06-01 00:00:00'::timestamptz, 'Хто змінив: Менеджер') ON CONFLICT (tenant_id, content_id) DO NOTHING;

-- ── distribution_template (6 рядків) ─────────────────────────────────────
INSERT INTO public.distribution_template (tenant_id, tmpl_id, category, description, default_percentage, fixed_amount, amount_currency, payment_form, is_active, notes) VALUES ('esco', 'TMPL-001', 'ЗП', 'Зарплата персоналу', 20, NULL, 'UAH', 'Готівка', true, 'Отримувач: Персонал') ON CONFLICT (tenant_id, tmpl_id) DO NOTHING;
INSERT INTO public.distribution_template (tenant_id, tmpl_id, category, description, default_percentage, fixed_amount, amount_currency, payment_form, is_active, notes) VALUES ('esco', 'TMPL-002', 'Дивіденди', 'Дивіденди власникам', 50, NULL, 'UAH', 'Карта', true, 'Отримувач: Власник') ON CONFLICT (tenant_id, tmpl_id) DO NOTHING;
INSERT INTO public.distribution_template (tenant_id, tmpl_id, category, description, default_percentage, fixed_amount, amount_currency, payment_form, is_active, notes) VALUES ('esco', 'TMPL-003', 'Резерв', 'Резерв компанії', 30, NULL, 'UAH', NULL, true, 'Отримувач: Резерв') ON CONFLICT (tenant_id, tmpl_id) DO NOTHING;
INSERT INTO public.distribution_template (tenant_id, tmpl_id, category, description, default_percentage, fixed_amount, amount_currency, payment_form, is_active, notes) VALUES ('esco', 'TMPL-004', 'ЗП CHF', 'Зарплата з CHF доходу', 20, NULL, 'CHF', 'Готівка', true, 'Отримувач: Персонал') ON CONFLICT (tenant_id, tmpl_id) DO NOTHING;
INSERT INTO public.distribution_template (tenant_id, tmpl_id, category, description, default_percentage, fixed_amount, amount_currency, payment_form, is_active, notes) VALUES ('esco', 'TMPL-005', 'Дивіденди CHF', 'Дивіденди з CHF', 50, NULL, 'CHF', 'Карта', true, 'Отримувач: Власник') ON CONFLICT (tenant_id, tmpl_id) DO NOTHING;
INSERT INTO public.distribution_template (tenant_id, tmpl_id, category, description, default_percentage, fixed_amount, amount_currency, payment_form, is_active, notes) VALUES ('esco', 'TMPL-006', 'Резерв CHF', 'Резерв з CHF', 30, NULL, 'CHF', NULL, true, 'Отримувач: Резерв') ON CONFLICT (tenant_id, tmpl_id) DO NOTHING;

-- ── notifications (5 рядків) ─────────────────────────────────────
INSERT INTO public.notifications (tenant_id, notif_id, notification_type, event_trigger, channel, template_text, is_active, sent_at, delivery_status, sent_message_text) VALUES ('esco', 'NTF-001', 'Шаблон', 'Бронювання підтверджено', 'SMS', 'Вітаємо {ПІБ}! Ваше бронювання на {ДАТА} підтверджено. EscoExpress', true, NULL, NULL, NULL) ON CONFLICT (tenant_id, notif_id) DO NOTHING;
INSERT INTO public.notifications (tenant_id, notif_id, notification_type, event_trigger, channel, template_text, is_active, sent_at, delivery_status, sent_message_text) VALUES ('esco', 'NTF-002', 'Шаблон', 'Рейс завтра', 'SMS', 'Нагадування: завтра о {ЧАС} виїзд. Місце {МІСЦЕ}, авто {АВТО}. EscoExpress', true, NULL, NULL, NULL) ON CONFLICT (tenant_id, notif_id) DO NOTHING;
INSERT INTO public.notifications (tenant_id, notif_id, notification_type, event_trigger, channel, template_text, is_active, sent_at, delivery_status, sent_message_text) VALUES ('esco', 'NTF-003', 'Шаблон', 'Посилка отримана', 'SMS', 'Посилка #{ТТН} отримана водієм. Очікуйте доставки. EscoExpress', true, NULL, NULL, NULL) ON CONFLICT (tenant_id, notif_id) DO NOTHING;
INSERT INTO public.notifications (tenant_id, notif_id, notification_type, event_trigger, channel, template_text, is_active, sent_at, delivery_status, sent_message_text) VALUES ('esco', 'NTF-004', 'Шаблон', 'Посилка доставлена', 'SMS', 'Посилка #{ТТН} доставлена {ДАТА}. Дякуємо! EscoExpress', true, NULL, NULL, NULL) ON CONFLICT (tenant_id, notif_id) DO NOTHING;
INSERT INTO public.notifications (tenant_id, notif_id, notification_type, event_trigger, channel, template_text, is_active, sent_at, delivery_status, sent_message_text) VALUES ('esco', 'NTF-005', 'Шаблон', 'Нагадування боргу', 'SMS', 'Шановний {ПІБ}, нагадуємо про борг {СУМА} {ВАЛЮТА}. EscoExpress', true, NULL, NULL, NULL) ON CONFLICT (tenant_id, notif_id) DO NOTHING;

-- ── clients_directory (3 рядків) ─────────────────────────────────────
INSERT INTO public.clients_directory (tenant_id, cli_id, smart_id, registered_at, last_activity, phone, additional_phone, full_name, email, direction, client_type, is_vip, in_stoplist, stoplist_reason, total_routes, total_packages, total_bookings, last_payment_date, debt_uah, debt_chf, debt_eur, debt_pln, debt_czk, driver_rating, driver_ratings_count, driver_total_score, manager_rating, manager_ratings_count, manager_total_score, internal_rating, bot_rating, bot_ratings_count, bot_total_score, emoji_positive, emoji_neutral, emoji_negative, last_three_comments, last_review, last_review_date, app_status, notes) VALUES ('esco', 'CLI-20230714-A1B2', '69140592', '2023-07-14 10:00:00'::timestamptz, '2025-06-06 15:00:00'::timestamptz, '+380991234567', '+380501234567', 'Іваненко Іван', 'ivan@email.com', 'УК → ЄВ', 'Постійний', true, false, NULL, 5, 3, 0, '2025-06-01 00:00:00'::timestamptz, 0, 200, 0, 0, 0, 4.8, 3, 14, 4.9, 2, 10, NULL, 5, 1, 5, 1, 0, 0, 'Все добре | Швидко | Рекомендую', 'Чудовий сервіс', '2025-06-01 00:00:00'::timestamptz, 'active', 'OUT_OF_RANGE: internal_rating(raw)=9.7') ON CONFLICT (tenant_id, cli_id) DO NOTHING;
INSERT INTO public.clients_directory (tenant_id, cli_id, smart_id, registered_at, last_activity, phone, additional_phone, full_name, email, direction, client_type, is_vip, in_stoplist, stoplist_reason, total_routes, total_packages, total_bookings, last_payment_date, debt_uah, debt_chf, debt_eur, debt_pln, debt_czk, driver_rating, driver_ratings_count, driver_total_score, manager_rating, manager_ratings_count, manager_total_score, internal_rating, bot_rating, bot_ratings_count, bot_total_score, emoji_positive, emoji_neutral, emoji_negative, last_three_comments, last_review, last_review_date, app_status, notes) VALUES ('esco', 'CLI-20260403-2786', NULL, '2026-04-03 21:16:03'::timestamptz, '2026-04-03 21:16:03'::timestamptz, '+380639763484', NULL, 'Богдан Цимбала', NULL, NULL, 'Новий', NULL, NULL, NULL, 0, 1, 0, NULL, 0, 0, 0, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'active', NULL) ON CONFLICT (tenant_id, cli_id) DO NOTHING;
INSERT INTO public.clients_directory (tenant_id, cli_id, smart_id, registered_at, last_activity, phone, additional_phone, full_name, email, direction, client_type, is_vip, in_stoplist, stoplist_reason, total_routes, total_packages, total_bookings, last_payment_date, debt_uah, debt_chf, debt_eur, debt_pln, debt_czk, driver_rating, driver_ratings_count, driver_total_score, manager_rating, manager_ratings_count, manager_total_score, internal_rating, bot_rating, bot_ratings_count, bot_total_score, emoji_positive, emoji_neutral, emoji_negative, last_three_comments, last_review, last_review_date, app_status, notes) VALUES ('esco', 'CLI-20260404-H95Q', NULL, '2026-04-04 00:55:05'::timestamptz, '2026-04-04 00:55:05'::timestamptz, '+380636363363', NULL, 'Марина Тестова', NULL, NULL, 'Новий', NULL, NULL, NULL, 0, 0, 0, NULL, 0, 0, 0, 0, 0, NULL, 0, 0, NULL, 0, 0, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'active', NULL) ON CONFLICT (tenant_id, cli_id) DO NOTHING;

-- ── staff (5 рядків) ─────────────────────────────────────
INSERT INTO public.staff (tenant_id, staff_id, full_name, phone, email, role, login, city_based, salary, salary_currency, employment_status, employment_date, last_activity, notes) VALUES ('esco', 'STF-003', 'Марʼяна', '955222526', 'kvitun100@gmail.com', 'manager', 'kvitun100@gmail.com', NULL, NULL, 'CHF', 'active', NULL, '2026-04-22 13:27:00'::timestamptz, NULL) ON CONFLICT (tenant_id, staff_id) DO NOTHING;
INSERT INTO public.staff (tenant_id, staff_id, full_name, phone, email, role, login, city_based, salary, salary_currency, employment_status, employment_date, last_activity, notes) VALUES ('esco', 'STF-004', 'Марина', NULL, 'marinashestakova208@gmail.com', 'manager', 'marinashestakova208@gmail.com', NULL, NULL, NULL, 'active', NULL, '2026-04-20 12:01:00'::timestamptz, NULL) ON CONFLICT (tenant_id, staff_id) DO NOTHING;
INSERT INTO public.staff (tenant_id, staff_id, full_name, phone, email, role, login, city_based, salary, salary_currency, employment_status, employment_date, last_activity, notes) VALUES ('esco', 'STF-20260410150349', 'Василь', NULL, 'vasylgrachovid@gmail.com', 'driver', 'vasylgrachovid@gmail.com', NULL, NULL, 'CHF', 'active', '2026-04-10 00:00:00'::timestamptz, '2026-04-10 15:31:00'::timestamptz, NULL) ON CONFLICT (tenant_id, staff_id) DO NOTHING;
INSERT INTO public.staff (tenant_id, staff_id, full_name, phone, email, role, login, city_based, salary, salary_currency, employment_status, employment_date, last_activity, notes) VALUES ('esco', 'STF-005', 'Богдан', NULL, 'vocet1987@gmail.com', 'manager', 'vocet1987@gmail.com', NULL, NULL, NULL, 'active', NULL, '2026-04-10 16:05:00'::timestamptz, NULL) ON CONFLICT (tenant_id, staff_id) DO NOTHING;
UPDATE public.staff SET role='owner', notes=concat_ws('; ', notes, 'Власник USR-OWN-002 (primary — у owner_account); Доступ: Всі таблиці'), updated_at=now() WHERE tenant_id='esco' AND lower(login)='vocet1987@gmail.com';

-- ── owner_account (1 рядків) ─────────────────────────────────────
INSERT INTO public.owner_account (tenant_id, legacy_id, full_name, phone, email, login, password_hash, api_token, two_fa_enabled, account_status, created_at, last_login, last_password_change, access_scope, notes) VALUES ('esco', 'USR-OWN-001', 'Власник Іван', '+380991234567', 'owner@escoexpress.com', 'owner', 'CHANGE_ME_ESCO_owner', 'token_api_here', true, 'active', '2023-01-01 10:00:00'::timestamptz, '2025-06-06 15:00:00'::timestamptz, '2025-06-01 00:00:00'::timestamptz, 'Всі таблиці', NULL) ON CONFLICT (tenant_id) DO NOTHING;

COMMIT;

-- Оновити кеш PostgREST.
NOTIFY pgrst, 'reload schema';