-- =========================================================================
-- ESCO MIGRATION — PHASE 4: PAYMENTS + ROUTES + DISPATCHES + ORDERS
-- =========================================================================
-- routes:     8
-- payments:   61
-- dispatches: 2
-- orders:     1
--
-- ВАЖЛИВО:
--   ALTER dispatches DROP NOT NULL для route_id, vehicle_id —
--   у xlsx обидва Відправки мають порожні RTE_ID/AUTO_ID,
--   без DROP NOT NULL 2 рядки не зайдуть → втратимо.
--
-- Порядок: routes → payments/dispatches/orders (FK lookup'и).
-- =========================================================================

BEGIN;

-- ── Schema changes ──────────────────────────────────────────────
ALTER TABLE public.routes ADD COLUMN IF NOT EXISTS extra_data jsonb;
ALTER TABLE public.dispatches ALTER COLUMN route_id DROP NOT NULL;
ALTER TABLE public.dispatches ALTER COLUMN vehicle_id DROP NOT NULL;

-- ── UNIQUE indexes ──────────────────────────────────────────────
CREATE UNIQUE INDEX IF NOT EXISTS routes_tenant_rte_uidx ON public.routes (tenant_id, rte_id);
CREATE UNIQUE INDEX IF NOT EXISTS payments_tenant_pay_uidx ON public.payments (tenant_id, pay_id);
CREATE UNIQUE INDEX IF NOT EXISTS dispatches_tenant_disp_uidx ON public.dispatches (tenant_id, dispatch_id);
CREATE UNIQUE INDEX IF NOT EXISTS orders_tenant_order_uidx ON public.orders (tenant_id, order_id);

-- ── routes (8) ───────────────────────────────────
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260408-DP83', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T07:00:00.000Z', NULL, 'Цюріх', NULL, NULL, NULL, 'Вільна розсадка', 'Tanushik Orzhitskaya', '+380991237838', NULL, NULL, NULL, NULL, 'Львів', 'St. Gallen', '1.0', '22.0', NULL, NULL, '{"sender_phone": "+380991237838", "amount": 99.0, "deposit": 1000.0, "deposit_currency": "UAH", "payment_status": "Частково"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260326-1R5F', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T00:00:00.000Z', NULL, 'Цюріх', NULL, NULL, NULL, 'Вільна розсадка', 'Katerina Bitner', '+380995224300', NULL, NULL, NULL, NULL, 'Львів', 'Hagenbuch ZH, Schulstrasse 6.', '2.0', '27.0', NULL, NULL, '{"sender_phone": "+380995224300", "amount": 197.0, "deposit": 2000.0, "deposit_currency": "UAH", "payment_status": "Частково"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260418-29NW', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T07:00:00.000Z', NULL, 'Цюріх', NULL, NULL, NULL, 'Вільна розсадка', 'Tania Tania', '+380966512105', NULL, NULL, NULL, NULL, 'Львів', 'Zurich', '1.0', '16.0', NULL, NULL, '{"sender_phone": "+380966512105", "amount": 81.0, "deposit": 1000.0, "deposit_currency": "UAH", "payment_status": "Частково"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260326-TEKR', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T00:00:00.000Z', NULL, 'Цюріх', NULL, NULL, NULL, 'Вільна розсадка', 'Bird .', '#ERROR!', NULL, NULL, NULL, NULL, 'Львів', 'Zurich', '2.0', '4.0', NULL, NULL, '{"sender_phone": "#ERROR!", "amount": 112.0, "deposit_currency": "UAH", "payment_status": "Не оплачено"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260411-VEEM', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T07:00:00.000Z', NULL, 'Женева', NULL, NULL, NULL, 'Вільна розсадка', 'Veronika', '+380678136688', NULL, NULL, NULL, NULL, 'Львів', 'Zurich', '1.0', '13.0', NULL, NULL, '{"sender_phone": "+380678136688", "amount": 72.0, "deposit": 1000.0, "deposit_currency": "UAH", "payment_status": "Частково"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260419-LUKZ', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T07:00:00.000Z', NULL, 'Женева', NULL, NULL, NULL, 'Вільна розсадка', 'Надія💞', '+380660507719', NULL, NULL, NULL, NULL, 'Львів', 'Zurich', '2.0', '10.0', NULL, NULL, '{"sender_phone": "+380660507719", "amount": 9500.0, "amount_currency": "UAH", "deposit": 2000.0, "deposit_currency": "UAH", "payment_status": "Оплачено"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260404-KZJJ', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T07:00:00.000Z', NULL, 'Женева', NULL, NULL, NULL, 'Вільна розсадка', 'Петро', '+380992427089', NULL, NULL, NULL, NULL, 'Львів', 'Lausanne', '1.0', '9.0', NULL, NULL, '{"sender_phone": "+380992427089", "amount": 60.0, "deposit": 1000.0, "deposit_currency": "UAH", "payment_status": "Частково"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;
INSERT INTO public.routes (tenant_id, rte_id, record_type, direction, pax_id_or_pkg_id, route_date, timing, vehicle_name, driver_name, driver_phone, city, seat_number, passenger_name, passenger_phone, sender_name, recipient_name, recipient_phone, recipient_address, departure_address, arrival_address, seats_count, baggage_weight, internal_number, ttn_number, extra_data) VALUES ('esco', 'PAX-20260326-Q3PJ', 'Пасажир', 'Україна-ЄВ', NULL, '2026-04-22T00:00:00.000Z', NULL, 'Женева', NULL, NULL, NULL, 'Вільна розсадка', 'Андрій', '+380981750005', NULL, NULL, NULL, NULL, 'Львів', 'Geneva', '2.0', '16.0', NULL, NULL, '{"sender_phone": "+380981750005", "amount": 114.0, "deposit": 2000.0, "deposit_currency": "UAH", "payment_status": "Частково"}'::jsonb) ON CONFLICT (tenant_id, rte_id) DO NOTHING;

-- ── payments (61) ───────────────────────────────
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20250601-001', '2025-06-01 10:00:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20250601-A1B2' LIMIT 1), (SELECT id FROM public.routes WHERE tenant_id='esco' AND rte_id='RTE-20250601-C1M4' LIMIT 1), NULL, '69140592', 'Завдаток', 1000, 'UAH', 'Готівка', 'Оплачено', 0, 'UAH', NULL, 'Хто вніс: Менеджер Оля') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20250601-002', '2025-06-01 10:05:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20250601-A1B2' LIMIT 1), (SELECT id FROM public.routes WHERE tenant_id='esco' AND rte_id='RTE-20250601-C1M4' LIMIT 1), NULL, '69140592', 'Квиток', 200, 'CHF', 'Готівка', 'Оплачено', 0, 'UAH', NULL, 'Хто вніс: Менеджер Оля') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20250601-003', '2025-06-01 10:10:00'::timestamptz, 'Менеджер', NULL, (SELECT id FROM public.routes WHERE tenant_id='esco' AND rte_id='RTE-20250601-C1M4' LIMIT 1), NULL, '69140593', 'Посилка', 300, 'CHF', 'Карта', 'Частково', 100, 'CHF', '2025-06-15'::date, 'Хто вніс: Менеджер Оля | залишок 100 CHF') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260327-B9WJ', '2026-03-27 12:42:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-DEO3' LIMIT 1), NULL, NULL, 240587246, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 0, 'UAH', NULL, 'Хто вніс: Менеджер 1 Мар’яна') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260327-BGB6', '2026-03-27 13:03:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-NJJZ' LIMIT 1), NULL, NULL, 169268977, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 0, 'UAH', NULL, 'Хто вніс: Богдан') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260327-KZIL', '2026-03-27 15:07:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-Q3PJ' LIMIT 1), NULL, NULL, 123678693, 'Завдаток', 2, 'UAH', NULL, 'Отримано', 48, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260327-ZBWX', '2026-03-27 15:08:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-Q3PJ' LIMIT 1), NULL, NULL, 123678693, 'Завдаток', 1998, 'UAH', NULL, 'Отримано', 0, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260402-3FD5', '2026-04-02 22:45:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260402-ED2U' LIMIT 1), NULL, NULL, 198483374, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Юляся') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260407-Y5YP', '2026-04-07 12:36:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260404-KZJJ' LIMIT 1), NULL, NULL, 218931355, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260407-ULPY', '2026-04-07 12:39:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260401-DTQU' LIMIT 1), NULL, NULL, 69600957, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260410-II5U', '2026-04-10 17:11:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-G45T' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-O5KV' LIMIT 1), 207897400, 'Повернення', 1000, 'UAH', NULL, 'Повернено', 50, 'UAH', NULL, 'Хто вніс: Менеджер 2') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260410-D3JU', '2026-04-10 17:13:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-WZOX' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-CBQ1' LIMIT 1), 198483374, 'Повернення', 1000, 'UAH', NULL, 'Повернено', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260410-C3XH', '2026-04-10 17:14:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-WZOX' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-CBQ1' LIMIT 1), 198483374, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260410-NACH', '2026-04-10 17:14:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-G45T' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-O5KV' LIMIT 1), 207897400, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 80, 'UAH', NULL, 'Хто вніс: Менеджер 2') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260410-6KVN', '2026-04-10 17:48:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260410-UM6F' LIMIT 1), NULL, NULL, 202071056, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 2') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260410-A059', '2026-04-10 17:54:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260410-13PJ' LIMIT 1), NULL, NULL, 159327790, 'Завдаток', 2000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 2') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260414-V7HC', '2026-04-14 10:44:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260412-QMA0' LIMIT 1), NULL, NULL, 120957165, 'Завдаток', 20, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260414-BZLO', '2026-04-14 10:44:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260412-QMA0' LIMIT 1), NULL, NULL, 120957165, 'Завдаток', 1980, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260415-7AJZ', '2026-04-15 15:28:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260415-V2HN' LIMIT 1), NULL, NULL, 114051309, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-WYJ3', '2026-04-16 14:35:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260403-U6QS' LIMIT 1), NULL, NULL, 150701201, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-IVSH', '2026-04-16 14:35:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260409-CH4N' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-Y1TE' LIMIT 1), 69085677, 'Завдаток', 2000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-U1T8', '2026-04-16 14:36:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260410-18EF' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-Y1TE' LIMIT 1), 241514629, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-FFXY', '2026-04-16 14:36:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260411-UF6X' LIMIT 1), NULL, NULL, 186284776, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-A1JW', '2026-04-16 14:37:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260412-EO7W' LIMIT 1), NULL, NULL, 120957165, 'Завдаток', 2000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-LUJ4', '2026-04-16 14:54:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260414-W0LE' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260410-IU2P' LIMIT 1), 239676161, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-1FTV', '2026-04-16 15:09:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260407-0A0B' LIMIT 1), NULL, NULL, 71479986, 'Завдаток', 1, 'UAH', NULL, 'Отримано', 70, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-2PCV', '2026-04-16 15:09:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260407-0A0B' LIMIT 1), NULL, NULL, 71479986, 'Завдаток', 99, 'UAH', NULL, 'Отримано', 70, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-VBB5', '2026-04-16 15:09:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260407-0A0B' LIMIT 1), NULL, NULL, 71479986, 'Завдаток', 900, 'UAH', NULL, 'Отримано', 70, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-ASXU', '2026-04-16 15:11:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260408-ULDN' LIMIT 1), NULL, NULL, 241144354, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 200, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-KF5C', '2026-04-16 15:28:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-I01U' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260410-RHIV' LIMIT 1), 239241134, 'Повернення', 18000, 'UAH', NULL, 'Повернено', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-LJ24', '2026-04-16 15:30:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260401-3NPY' LIMIT 1), NULL, NULL, 166439887, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-HR86', '2026-04-16 15:33:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-I01U' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260410-RHIV' LIMIT 1), 239241134, 'Завдаток', 300, 'CHF', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-9GFX', '2026-04-16 15:36:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260407-P9I6' LIMIT 1), NULL, NULL, 240306221, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-9CSL', '2026-04-16 15:40:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-V7FT' LIMIT 1), NULL, NULL, 166627105, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-D2TZ', '2026-04-16 15:42:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260404-VPC3' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260410-730X' LIMIT 1), 213534622, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-23W2', '2026-04-16 15:44:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260407-CS92' LIMIT 1), NULL, NULL, 66015171, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-Q4UY', '2026-04-16 15:44:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260401-LWJB' LIMIT 1), NULL, NULL, 209709583, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-CXL4', '2026-04-16 15:45:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260415-KWP7' LIMIT 1), NULL, NULL, 198483374, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-HZZO', '2026-04-16 15:47:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260408-JHEX' LIMIT 1), NULL, NULL, 80719929, 'Завдаток', 2000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260416-N75O', '2026-04-16 19:17:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260416-J5PG' LIMIT 1), NULL, NULL, 241203415, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-I2DD', '2026-04-17 09:29:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260329-VWGE' LIMIT 1), NULL, NULL, 238558798, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-6GSZ', '2026-04-17 09:50:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260413-YFSC' LIMIT 1), NULL, NULL, 65752476, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-AGDD', '2026-04-17 09:59:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260411-WF1H' LIMIT 1), NULL, NULL, 113403537, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-TNIB', '2026-04-17 10:04:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-VAME' LIMIT 1), NULL, NULL, 239752262, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 100, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-Z6B5', '2026-04-17 10:05:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260413-0A75' LIMIT 1), NULL, NULL, 76314504, 'Завдаток', 100, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-VAQ2', '2026-04-17 10:11:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-O8WY' LIMIT 1), NULL, NULL, 166627105, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 100, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-PFJ6', '2026-04-17 10:25:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260407-N842' LIMIT 1), NULL, NULL, 195535409, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-L56L', '2026-04-17 10:27:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260408-V1VS' LIMIT 1), NULL, NULL, 240306221, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-PW9B', '2026-04-17 10:28:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260404-BUYG' LIMIT 1), NULL, NULL, 213534622, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-HY0U', '2026-04-17 10:28:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260404-BUYG' LIMIT 1), NULL, NULL, 213534622, 'Повернення', 900, 'UAH', NULL, 'Повернено', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-15MK', '2026-04-17 10:28:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260404-BUYG' LIMIT 1), NULL, NULL, 213534622, 'Завдаток', 900, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-HCNB', '2026-04-17 10:30:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260331-3TZD' LIMIT 1), NULL, NULL, 217867564, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260417-M7K6', '2026-04-17 18:04:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260417-M5B3' LIMIT 1), NULL, NULL, 241203415, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260418-Q1P4', '2026-04-18 17:01:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260418-29NW' LIMIT 1), NULL, NULL, 235847251, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 50, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260418-WNVT', '2026-04-18 17:03:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260417-2QS4' LIMIT 1), NULL, NULL, 107210247, 'Завдаток', 2000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260420-1VED', '2026-04-20 20:25:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260419-LUKZ' LIMIT 1), NULL, NULL, 163051858, 'Завдаток', 2000, 'UAH', NULL, 'Отримано', 180, 'UAH', NULL, 'Хто вніс: Менеджер 3') ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260422-5AQP', '2026-04-22 10:09:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260326-TEKR' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-WZIZ' LIMIT 1), 240133214, 'Повернення', 2000, 'UAH', NULL, 'Повернено', 50, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260422-M667', '2026-04-22 10:13:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260408-DP83' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-KWSP' LIMIT 1), 94436688, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 99, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260422-GK2I', '2026-04-22 10:16:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260411-VEEM' LIMIT 1), NULL, (SELECT id FROM public.calendar WHERE tenant_id='esco' AND cal_id='CAL-20260403-WZIZ' LIMIT 1), 194587541, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 72, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260422-GW17', '2026-04-22 12:41:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260421-LTU1' LIMIT 1), NULL, NULL, 241877713, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;
INSERT INTO public.payments (tenant_id, pay_id, created_at, created_by_role, passenger_id, route_id, calendar_id, smart_id, payment_type, amount, amount_currency, payment_form, payment_status, debt_amount, debt_currency, due_date, notes) VALUES ('esco', 'PAY-20260422-LCHJ', '2026-04-22 13:00:00'::timestamptz, 'Менеджер', (SELECT id FROM public.passengers WHERE tenant_id='esco' AND pax_id='PAX-20260421-QHXB' LIMIT 1), NULL, NULL, 63761951, 'Завдаток', 1000, 'UAH', NULL, 'Отримано', 130, 'UAH', NULL, NULL) ON CONFLICT (tenant_id, pay_id) DO NOTHING;

-- ── dispatches (2) ───────────────────────────
INSERT INTO public.dispatches (tenant_id, dispatch_id, created_at, route_id, route_date, vehicle_id, sender_name, sender_phone, registrar_phone, recipient_name, recipient_phone, recipient_address, internal_number, weight_kg, package_description, photo_url, amount, amount_currency, deposit, deposit_currency, payment_form, payment_status, debt, status, notes) VALUES ('esco', 'DISP_20260404_001857', '2026-04-04 00:00:00'::timestamptz, NULL, '2026-04-15'::date, NULL, 'Степан', '380973636', '380973636', 'Оленка', '+34657557549494', 'Мадрид', NULL, 10, 'ліки', NULL, 100, 'USD', NULL, 'UAH', NULL, 'pending', NULL, 'cancelled', 'Водій: Степан | тест | RTE_ID(raw)=порожнє у джерелі | AUTO_ID(raw)=порожнє у джерелі') ON CONFLICT (tenant_id, dispatch_id) DO NOTHING;
INSERT INTO public.dispatches (tenant_id, dispatch_id, created_at, route_id, route_date, vehicle_id, sender_name, sender_phone, registrar_phone, recipient_name, recipient_phone, recipient_address, internal_number, weight_kg, package_description, photo_url, amount, amount_currency, deposit, deposit_currency, payment_form, payment_status, debt, status, notes) VALUES ('esco', 'DISP_20260409_195529', '2026-04-09 00:00:00'::timestamptz, NULL, NULL, NULL, NULL, '+380679767484', '+380679767484', NULL, '+380639763484', 'Львів 4', 200, 2, 'Польська чорна клітка', NULL, 499, 'CHF', 500, 'EUR', 'Готівка', 'pending', 8, 'pending', 'Водій: 1.0 | К-сть місць: 1 | RTE_ID(raw)=порожнє у джерелі | AUTO_ID(raw)=порожнє у джерелі') ON CONFLICT (tenant_id, dispatch_id) DO NOTHING;

-- ── orders (1) ───────────────────────────────────
INSERT INTO public.orders (tenant_id, order_id, client_id, created_at, direction, sender_address, recipient_address, recipient_phone, weight_kg, description, photo_url, price, price_currency, payment_status, package_status, delivery_date, client_notes, manager_notes) VALUES ('esco', 'ORD-20260403-9313', (SELECT id FROM public.clients_directory WHERE tenant_id='esco' AND cli_id='CLI-20260403-2786' LIMIT 1), '2026-04-03 23:20:32'::timestamptz, 'UA → EU', '(не вказано)', 'Цюрих, Dorflistrasse 90, 8050 Zürich', '382000000', NULL, 'Особисті речі', NULL, NULL, 'EUR', 'Не оплачено', 'Нове', NULL, NULL, NULL) ON CONFLICT (tenant_id, order_id) DO NOTHING;

COMMIT;

NOTIFY pgrst, 'reload schema';