-- 2026-04-27 — Passenger sync v2: PAX_ID generated by us, smart_id stored separately,
-- dedup by (tenant_id, smart_id, booking_created_at).
--
-- ПЕРЕДУМОВА
-- ----------
-- Стара версія create_passenger_from_sheet генерувала pax_id = 'PAX_' + smart_id.
-- Це означало: один SmartSender контакт = один лід назавжди. Якщо клієнт
-- замовляв вдруге (новий рядок у бот-таблиці, інша дата створення) — RPC
-- казав «уже є в БД, пропускаю». Усі повторні замовлення втрачались.
--
-- НОВА МОДЕЛЬ
-- ----------
-- - pax_id — наш внутрішній ID, генерується GAS-скриптом як 'PAX_<timestamp_ms>'.
--   Унікальний для кожного **бронювання** (а не для людини).
-- - smart_id — окрема колонка, повторюється у різних лідів того самого клієнта.
-- - Дедуп — за `(tenant_id, smart_id, booking_created_at)` точно до секунди.
--   Той самий клієнт + той самий момент бронювання = той самий лід → пропуск.
--
-- ЕФЕКТ
-- -----
-- Старі 272 записи з форматом pax_id='PAX_<smart_id>' лишаються недоторканими.
-- Нові заявки приходять у форматі pax_id='PAX_<ts>'. Поверненці (Rossmari etc)
-- тепер отримують окрему картку на кожне бронювання.

BEGIN;

-- ─── 1. Індекс для швидкого дедупу ─────────────────────────────────────────
-- Точний матч (tenant_id, smart_id, booking_created_at) має бути миттєвим,
-- бо RPC робить EXISTS-перевірку на КОЖНОМУ виклику з GAS (раз на кожен рядок).
CREATE INDEX IF NOT EXISTS passengers_smart_booking_idx
    ON public.passengers (tenant_id, smart_id, booking_created_at)
    WHERE coalesce(is_archived, false) = false AND smart_id IS NOT NULL;


-- ─── 2. Нова RPC create_passenger_from_sheet ───────────────────────────────
-- Вхідний payload (snake_case, рядки):
--   pax_id              ← ОБОВ'ЯЗКОВО, GAS генерує 'PAX_<timestamp_ms>'
--   smart_id            SmartSender ID (зберігається окремо, не в pax_id)
--   direction           'Україна-ЄВ' | 'Європа-УК'
--   full_name | phone   хоча б одне
--   booking_created_at  ISO timestamptz — точно до секунди
--   ...решта поля як були (ticket_price, deposit, departure_date, тощо)
--
-- Поведінка:
--   Якщо в БД уже є активний лід з тим самим smart_id + booking_created_at
--   (тенант той самий) → повертаємо NULL (фронтенд GAS бачить як SKIPPED_DUPLICATE).
--   Інакше → INSERT з переданим pax_id, повертаємо pax_id.
--
-- Старі записи з pax_id='PAX_<smart_id>' (без знаку нашого нового формату)
-- НЕ ЗАЧІПАЄМО. Вони дедупляться нормально, бо мають smart_id+booking_created_at.

CREATE OR REPLACE FUNCTION public.create_passenger_from_sheet(payload jsonb)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $fn$
DECLARE
    v_tenant      text := 'esco';
    v_pax_id      text := btrim(coalesce(payload->>'pax_id', ''));
    v_smart_id    text := nullif(btrim(coalesce(payload->>'smart_id', '')), '');
    v_full_name   text := nullif(btrim(coalesce(payload->>'full_name', '')), '');
    v_phone       text := nullif(btrim(coalesce(payload->>'phone', '')), '');
    v_direction   text := btrim(coalesce(payload->>'direction', ''));
    v_lead_status text := coalesce(
        nullif(btrim(coalesce(payload->>'lead_status', '')), ''),
        'Новий'
    );
    v_booking_at  timestamptz := nullif(payload->>'booking_created_at', '')::timestamptz;
    v_inserted    text;
BEGIN
    -- Вхідна валідація
    IF v_pax_id = '' THEN
        RAISE EXCEPTION 'pax_id обов''язковий';
    END IF;
    IF v_full_name IS NULL AND v_phone IS NULL THEN
        RAISE EXCEPTION 'потрібно хоча б full_name або phone';
    END IF;
    IF v_direction NOT IN ('Україна-ЄВ', 'Європа-УК') THEN
        RAISE EXCEPTION
            'direction має бути ''Україна-ЄВ'' або ''Європа-УК'', отримано: "%"',
            v_direction;
    END IF;

    -- ── Дедуп по (tenant_id, smart_id, booking_created_at) ────────────────
    -- Якщо такий лід уже є — поводимось як дубль (NULL).
    -- Не дедуплимо коли smart_id або booking_created_at нема — тоді
    -- вставляємо як новий, бо без них немає чим однозначно ідентифікувати.
    IF v_smart_id IS NOT NULL AND v_booking_at IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM public.passengers
            WHERE tenant_id = v_tenant
              AND smart_id = v_smart_id
              AND booking_created_at = v_booking_at
              AND coalesce(is_archived, false) = false
        ) THEN
            RETURN NULL;
        END IF;
    END IF;

    -- ── INSERT ────────────────────────────────────────────────────────────
    INSERT INTO public.passengers (
        pax_id, tenant_id, direction, source_sheet,
        smart_id,
        full_name, phone, registrar_phone,
        seats_count,
        deposit, deposit_currency,
        ticket_price, ticket_currency,
        booking_created_at, departure_date,
        lead_status, crm_status, is_archived,
        seat_number,
        arrival_address, departure_address,
        notes,
        created_at, updated_at
    )
    VALUES (
        v_pax_id, v_tenant, v_direction,
        nullif(payload->>'source_sheet', ''),
        v_smart_id,
        v_full_name, v_phone,
        nullif(btrim(coalesce(payload->>'registrar_phone', '')), ''),
        nullif(payload->>'seats_count', '')::numeric,
        nullif(payload->>'deposit', '')::numeric,
        coalesce(nullif(payload->>'deposit_currency', ''), 'CHF'),
        nullif(payload->>'ticket_price', '')::numeric,
        coalesce(nullif(payload->>'ticket_currency', ''), 'CHF'),
        v_booking_at,
        nullif(payload->>'departure_date', '')::date,
        v_lead_status, 'active', false,
        nullif(payload->>'seat_number', ''),
        nullif(payload->>'arrival_address', ''),
        nullif(payload->>'departure_address', ''),
        nullif(payload->>'notes', ''),
        now(), now()
    )
    ON CONFLICT (tenant_id, pax_id) DO NOTHING
    RETURNING pax_id INTO v_inserted;

    RETURN v_inserted;
END;
$fn$;

COMMENT ON FUNCTION public.create_passenger_from_sheet(jsonb) IS
    'v2: pax_id ззовні, dedup by (tenant_id, smart_id, booking_created_at). Returns pax_id or NULL on duplicate.';

REVOKE ALL ON FUNCTION public.create_passenger_from_sheet(jsonb) FROM public;
GRANT EXECUTE ON FUNCTION public.create_passenger_from_sheet(jsonb)
    TO anon, authenticated, service_role;

COMMIT;

NOTIFY pgrst, 'reload schema';
